// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: websocket/v1/websocket.proto

package websocketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderId       string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderUsername string                 `protobuf:"bytes,3,opt,name=sender_username,json=senderUsername,proto3" json:"sender_username,omitempty"`
	RoomId         string                 `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EventType      string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Data           []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebSocketEvent) Reset() {
	*x = WebSocketEvent{}
	mi := &file_websocket_v1_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketEvent) ProtoMessage() {}

func (x *WebSocketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketEvent.ProtoReflect.Descriptor instead.
func (*WebSocketEvent) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *WebSocketEvent) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *WebSocketEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *WebSocketEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WebSocketEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_websocket_v1_websocket_proto protoreflect.FileDescriptor

const file_websocket_v1_websocket_proto_rawDesc = "" +
	"\n" +
	"\x1cwebsocket/v1/websocket.proto\x12\fwebsocket.v1\"\xa2\x01\n" +
	"\x0eWebSocketEvent\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12'\n" +
	"\x0fsender_username\x18\x03 \x01(\tR\x0esenderUsername\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04dataB-Z+main/pkg/proto/gen/websocket/v1;websocketv1b\x06proto3"

var (
	file_websocket_v1_websocket_proto_rawDescOnce sync.Once
	file_websocket_v1_websocket_proto_rawDescData []byte
)

func file_websocket_v1_websocket_proto_rawDescGZIP() []byte {
	file_websocket_v1_websocket_proto_rawDescOnce.Do(func() {
		file_websocket_v1_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_v1_websocket_proto_rawDesc), len(file_websocket_v1_websocket_proto_rawDesc)))
	})
	return file_websocket_v1_websocket_proto_rawDescData
}

var file_websocket_v1_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_websocket_v1_websocket_proto_goTypes = []any{
	(*WebSocketEvent)(nil), // 0: websocket.v1.WebSocketEvent
}
var file_websocket_v1_websocket_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_websocket_v1_websocket_proto_init() }
func file_websocket_v1_websocket_proto_init() {
	if File_websocket_v1_websocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_v1_websocket_proto_rawDesc), len(file_websocket_v1_websocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_websocket_v1_websocket_proto_goTypes,
		DependencyIndexes: file_websocket_v1_websocket_proto_depIdxs,
		MessageInfos:      file_websocket_v1_websocket_proto_msgTypes,
	}.Build()
	File_websocket_v1_websocket_proto = out.File
	file_websocket_v1_websocket_proto_goTypes = nil
	file_websocket_v1_websocket_proto_depIdxs = nil
}
