// Code generated by MockGen. DO NOT EDIT.
// Source: message_usecase.go
//
// Generated by this command:
//
//	mockgen -source=message_usecase.go -destination=mock/message_mocks.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "main/internal/domain/entity"
	events "main/internal/domain/events"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockChatInterface is a mock of ChatInterface interface.
type MockChatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChatInterfaceMockRecorder
	isgomock struct{}
}

// MockChatInterfaceMockRecorder is the mock recorder for MockChatInterface.
type MockChatInterfaceMockRecorder struct {
	mock *MockChatInterface
}

// NewMockChatInterface creates a new mock instance.
func NewMockChatInterface(ctrl *gomock.Controller) *MockChatInterface {
	mock := &MockChatInterface{ctrl: ctrl}
	mock.recorder = &MockChatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatInterface) EXPECT() *MockChatInterfaceMockRecorder {
	return m.recorder
}

// CheckIsMemberOfChat mocks base method.
func (m *MockChatInterface) CheckIsMemberOfChat(ctx context.Context, chatID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsMemberOfChat", ctx, chatID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIsMemberOfChat indicates an expected call of CheckIsMemberOfChat.
func (mr *MockChatInterfaceMockRecorder) CheckIsMemberOfChat(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsMemberOfChat", reflect.TypeOf((*MockChatInterface)(nil).CheckIsMemberOfChat), ctx, chatID, userID)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageRepository) DeleteMessage(ctx context.Context, senderID, chatID int64, msgID []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, senderID, chatID, msgID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageRepositoryMockRecorder) DeleteMessage(ctx, senderID, chatID, msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageRepository)(nil).DeleteMessage), ctx, senderID, chatID, msgID)
}

// EditMessage mocks base method.
func (m *MockMessageRepository) EditMessage(ctx context.Context, senderID, chatID int64, msgID, newText string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessage", ctx, senderID, chatID, msgID, newText)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockMessageRepositoryMockRecorder) EditMessage(ctx, senderID, chatID, msgID, newText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockMessageRepository)(nil).EditMessage), ctx, senderID, chatID, msgID, newText)
}

// GetMessages mocks base method.
func (m *MockMessageRepository) GetMessages(ctx context.Context, chatID int64, anchorTime time.Time, anchorID string, limit int64) ([]entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, chatID, anchorTime, anchorID, limit)
	ret0, _ := ret[0].([]entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockMessageRepositoryMockRecorder) GetMessages(ctx, chatID, anchorTime, anchorID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetMessages), ctx, chatID, anchorTime, anchorID, limit)
}

// SaveMessage mocks base method.
func (m *MockMessageRepository) SaveMessage(ctx context.Context, msg any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageRepositoryMockRecorder) SaveMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageRepository)(nil).SaveMessage), ctx, msg)
}

// MockKafkaProducer is a mock of KafkaProducer interface.
type MockKafkaProducer struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaProducerMockRecorder
	isgomock struct{}
}

// MockKafkaProducerMockRecorder is the mock recorder for MockKafkaProducer.
type MockKafkaProducerMockRecorder struct {
	mock *MockKafkaProducer
}

// NewMockKafkaProducer creates a new mock instance.
func NewMockKafkaProducer(ctrl *gomock.Controller) *MockKafkaProducer {
	mock := &MockKafkaProducer{ctrl: ctrl}
	mock.recorder = &MockKafkaProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaProducer) EXPECT() *MockKafkaProducerMockRecorder {
	return m.recorder
}

// SendMessageCreated mocks base method.
func (m *MockKafkaProducer) SendMessageCreated(ctx context.Context, event events.EventMessageCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageCreated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageCreated indicates an expected call of SendMessageCreated.
func (mr *MockKafkaProducerMockRecorder) SendMessageCreated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageCreated", reflect.TypeOf((*MockKafkaProducer)(nil).SendMessageCreated), ctx, event)
}
