// Code generated by MockGen. DO NOT EDIT.
// Source: message_service.go
//
// Generated by this command:
//
//	mockgen -source=message_service.go -destination=mock/message_mocks.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "main/internal/domain/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChatInterface is a mock of ChatInterface interface.
type MockChatInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChatInterfaceMockRecorder
	isgomock struct{}
}

// MockChatInterfaceMockRecorder is the mock recorder for MockChatInterface.
type MockChatInterfaceMockRecorder struct {
	mock *MockChatInterface
}

// NewMockChatInterface creates a new mock instance.
func NewMockChatInterface(ctrl *gomock.Controller) *MockChatInterface {
	mock := &MockChatInterface{ctrl: ctrl}
	mock.recorder = &MockChatInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatInterface) EXPECT() *MockChatInterfaceMockRecorder {
	return m.recorder
}

// CheckIsMemberOfChat mocks base method.
func (m *MockChatInterface) CheckIsMemberOfChat(ctx context.Context, chatID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsMemberOfChat", ctx, chatID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIsMemberOfChat indicates an expected call of CheckIsMemberOfChat.
func (mr *MockChatInterfaceMockRecorder) CheckIsMemberOfChat(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsMemberOfChat", reflect.TypeOf((*MockChatInterface)(nil).CheckIsMemberOfChat), ctx, chatID, userID)
}

// MockMessageInterface is a mock of MessageInterface interface.
type MockMessageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMessageInterfaceMockRecorder
	isgomock struct{}
}

// MockMessageInterfaceMockRecorder is the mock recorder for MockMessageInterface.
type MockMessageInterfaceMockRecorder struct {
	mock *MockMessageInterface
}

// NewMockMessageInterface creates a new mock instance.
func NewMockMessageInterface(ctrl *gomock.Controller) *MockMessageInterface {
	mock := &MockMessageInterface{ctrl: ctrl}
	mock.recorder = &MockMessageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageInterface) EXPECT() *MockMessageInterfaceMockRecorder {
	return m.recorder
}

// CheckMessageExists mocks base method.
func (m *MockMessageInterface) CheckMessageExists(ctx context.Context, messageID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMessageExists", ctx, messageID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMessageExists indicates an expected call of CheckMessageExists.
func (mr *MockMessageInterfaceMockRecorder) CheckMessageExists(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMessageExists", reflect.TypeOf((*MockMessageInterface)(nil).CheckMessageExists), ctx, messageID)
}

// Create mocks base method.
func (m *MockMessageInterface) Create(ctx context.Context, chatID, userID int64, senderUsername, text string) (entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, chatID, userID, senderUsername, text)
	ret0, _ := ret[0].(entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMessageInterfaceMockRecorder) Create(ctx, chatID, userID, senderUsername, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageInterface)(nil).Create), ctx, chatID, userID, senderUsername, text)
}

// DeleteMessage mocks base method.
func (m *MockMessageInterface) DeleteMessage(ctx context.Context, messageID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageInterfaceMockRecorder) DeleteMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageInterface)(nil).DeleteMessage), ctx, messageID)
}

// EditMessage mocks base method.
func (m *MockMessageInterface) EditMessage(ctx context.Context, messageID int64, newText string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMessage", ctx, messageID, newText)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockMessageInterfaceMockRecorder) EditMessage(ctx, messageID, newText any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockMessageInterface)(nil).EditMessage), ctx, messageID, newText)
}

// ListByChat mocks base method.
func (m *MockMessageInterface) ListByChat(ctx context.Context, chatID int64) ([]entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByChat", ctx, chatID)
	ret0, _ := ret[0].([]entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByChat indicates an expected call of ListByChat.
func (mr *MockMessageInterfaceMockRecorder) ListByChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByChat", reflect.TypeOf((*MockMessageInterface)(nil).ListByChat), ctx, chatID)
}
