// Code generated by MockGen. DO NOT EDIT.
// Source: chat_usecase.go
//
// Generated by this command:
//
//	mockgen -source=chat_usecase.go -destination=mock/chat_mocks.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "main/internal/domain/entity"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockChatRepositoryInterface is a mock of ChatRepositoryInterface interface.
type MockChatRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChatRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockChatRepositoryInterfaceMockRecorder is the mock recorder for MockChatRepositoryInterface.
type MockChatRepositoryInterfaceMockRecorder struct {
	mock *MockChatRepositoryInterface
}

// NewMockChatRepositoryInterface creates a new mock instance.
func NewMockChatRepositoryInterface(ctrl *gomock.Controller) *MockChatRepositoryInterface {
	mock := &MockChatRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockChatRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRepositoryInterface) EXPECT() *MockChatRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddMembers mocks base method.
func (m *MockChatRepositoryInterface) AddMembers(ctx context.Context, chatID int64, members []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembers", ctx, chatID, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMembers indicates an expected call of AddMembers.
func (mr *MockChatRepositoryInterfaceMockRecorder) AddMembers(ctx, chatID, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembers", reflect.TypeOf((*MockChatRepositoryInterface)(nil).AddMembers), ctx, chatID, members)
}

// CheckIfChatExists mocks base method.
func (m *MockChatRepositoryInterface) CheckIfChatExists(ctx context.Context, chatID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIfChatExists", ctx, chatID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIfChatExists indicates an expected call of CheckIfChatExists.
func (mr *MockChatRepositoryInterfaceMockRecorder) CheckIfChatExists(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIfChatExists", reflect.TypeOf((*MockChatRepositoryInterface)(nil).CheckIfChatExists), ctx, chatID)
}

// CheckIsMemberOfChat mocks base method.
func (m *MockChatRepositoryInterface) CheckIsMemberOfChat(ctx context.Context, chatID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIsMemberOfChat", ctx, chatID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIsMemberOfChat indicates an expected call of CheckIsMemberOfChat.
func (mr *MockChatRepositoryInterfaceMockRecorder) CheckIsMemberOfChat(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIsMemberOfChat", reflect.TypeOf((*MockChatRepositoryInterface)(nil).CheckIsMemberOfChat), ctx, chatID, userID)
}

// CreateChat mocks base method.
func (m *MockChatRepositoryInterface) CreateChat(ctx context.Context, title string, isPrivate bool, members []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, title, isPrivate, members)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatRepositoryInterfaceMockRecorder) CreateChat(ctx, title, isPrivate, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatRepositoryInterface)(nil).CreateChat), ctx, title, isPrivate, members)
}

// DeleteChat mocks base method.
func (m *MockChatRepositoryInterface) DeleteChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatRepositoryInterfaceMockRecorder) DeleteChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatRepositoryInterface)(nil).DeleteChat), ctx, chatID)
}

// GetChatDetails mocks base method.
func (m *MockChatRepositoryInterface) GetChatDetails(ctx context.Context, chatID int64) (entity.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatDetails", ctx, chatID)
	ret0, _ := ret[0].(entity.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatDetails indicates an expected call of GetChatDetails.
func (mr *MockChatRepositoryInterfaceMockRecorder) GetChatDetails(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatDetails", reflect.TypeOf((*MockChatRepositoryInterface)(nil).GetChatDetails), ctx, chatID)
}

// ListOfChats mocks base method.
func (m *MockChatRepositoryInterface) ListOfChats(ctx context.Context, userID int64) ([]entity.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOfChats", ctx, userID)
	ret0, _ := ret[0].([]entity.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOfChats indicates an expected call of ListOfChats.
func (mr *MockChatRepositoryInterfaceMockRecorder) ListOfChats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOfChats", reflect.TypeOf((*MockChatRepositoryInterface)(nil).ListOfChats), ctx, userID)
}

// RemoveMember mocks base method.
func (m *MockChatRepositoryInterface) RemoveMember(ctx context.Context, chatID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, chatID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockChatRepositoryInterfaceMockRecorder) RemoveMember(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockChatRepositoryInterface)(nil).RemoveMember), ctx, chatID, userID)
}

// MockMessageRepositoryInterface is a mock of MessageRepositoryInterface interface.
type MockMessageRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryInterfaceMockRecorder is the mock recorder for MockMessageRepositoryInterface.
type MockMessageRepositoryInterfaceMockRecorder struct {
	mock *MockMessageRepositoryInterface
}

// NewMockMessageRepositoryInterface creates a new mock instance.
func NewMockMessageRepositoryInterface(ctrl *gomock.Controller) *MockMessageRepositoryInterface {
	mock := &MockMessageRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepositoryInterface) EXPECT() *MockMessageRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockMessageRepositoryInterface) GetMessages(ctx context.Context, chatID int64, anchorTime time.Time) ([]entity.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, chatID, anchorTime)
	ret0, _ := ret[0].([]entity.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockMessageRepositoryInterfaceMockRecorder) GetMessages(ctx, chatID, anchorTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockMessageRepositoryInterface)(nil).GetMessages), ctx, chatID, anchorTime)
}

// MockUserInterface is a mock of UserInterface interface.
type MockUserInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserInterfaceMockRecorder
	isgomock struct{}
}

// MockUserInterfaceMockRecorder is the mock recorder for MockUserInterface.
type MockUserInterfaceMockRecorder struct {
	mock *MockUserInterface
}

// NewMockUserInterface creates a new mock instance.
func NewMockUserInterface(ctrl *gomock.Controller) *MockUserInterface {
	mock := &MockUserInterface{ctrl: ctrl}
	mock.recorder = &MockUserInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInterface) EXPECT() *MockUserInterfaceMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockUserInterface) CheckUserExists(ctx context.Context, userID int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", ctx, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockUserInterfaceMockRecorder) CheckUserExists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockUserInterface)(nil).CheckUserExists), ctx, userID)
}
